# fly.toml app configuration file generated for zen-demo-java on 2025-01-28T15:42:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-java'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
