# fly.toml app configuration file generated for zen-demo-java on 2025-01-28T15:42:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-java'
primary_region = 'ams'

[metrics]
  port = 9400
  path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
